#pragma once
#define TOTAL_SOUNDS 7224 + EXTRA_SOUNDS
#define EXTRA_SOUNDS TOTAL_NEW_SOUNDS + (VOICE_AMOUNT * NEW_VOICES)
#include "sound_bank.h"
#include "build_config.h"

typedef struct {
	int field0;
	int field4;
	int field8;
	int field12;
	float volume;
	int field20;
	int field24;
}sound_entry;

enum eNewSounds {
	SOUND_SONYA_SELECT = 7224,
	SOUND_SONYA_WINS = 7225,
	SOUND_KITANA_SELECT,
	SOUND_KITANA_WINS,
	SOUND_ONAGA_SELECT,
	SOUND_KITANA_FANLIFT,
	SOUND_KITANA_KISS,
	SOUND_KITANA_FAT_STRETCH,
	SOUND_KITANA_FAT_UNSTRETCH,
	SOUND_KITANA_FAT_BLOWUP,
	SOUND_JAX_FAT_SPLAT,
	SOUND_JAX_SP_GUN,
	SOUND_JAX_SELECT,
	SOUND_JAX_WINS,
	SOUND_FROST_SLIDE,
	SOUND_FROST_GROUND_FREEZE,
	SOUND_FROST_FATALITY_CHARGE,
	SOUND_FROST_FATALITY_BLOWUP,
	SOUND_FROST_FREEZE,
	SOUND_FROST_FATALITY_FREEZE,
	SOUND_FROST_SELECT,
	SOUND_FROST_WINS,
	SOUND_BLAZE_FLAMELOOP,
	SOUND_BLAZE_FLAMEBALL,
	SOUND_BLAZE_BALLHIT,
	SOUND_BLAZE_BALLBLOCK,
	SOUND_BLAZE_SELECT,
	SOUND_BLAZE_WINS,
	SOUND_SHAO_SELECT = 7344,
	SOUND_SHAO_WINS,
	SOUND_SHAO_KNEE,
	SOUND_SHAO_FIREBALL,
	SOUND_SHAO_FIREBALL_HIT,
	SOUND_SHAO_FIREBALL_BLOCKED,
	SOUND_SHAO_FORCEFIELD,
	SOUND_SHAO_FORCEFIELD_REACT,
	SOUND_SHAO_FORCEFIELD_DIE,
	SOUND_SHAO_GETUP,
	SOUND_SHAO_8,
	SOUND_SHAO_9,
	SOUND_SHAO_10,
	SOUND_SHAO_11,
	SOUND_SHAO_12,
	SOUND_SHAO_13,
	SOUND_SHAO_14,
	SOUND_SHAO_15,
	SOUND_SHAO_16,
	SOUND_SHAO_17,
	SOUND_SHAO_18,
	SOUND_SHAO_19,
	SOUND_SHAO_20,
	SOUND_SHAO_HK,
	SOUND_SHAO_22,
	SOUND_SHAO_23,
	SOUND_SHAO_24,
	SOUND_SHAO_25,
	SOUND_SHAO_26,
	SOUND_SHAO_27,
	SOUND_SHAO_28,
	SOUND_SHAO_29,
	SOUND_SHAO_30,
	SOUND_SHAO_31,
	SOUND_SHAO_32,
	SOUND_SHAO_33,
	SOUND_SHAO_34,
	SOUND_SHAO_35,
	SOUND_SHAO_36,
	SOUND_SHAO_37,
	SOUND_SHAO_38,
	SOUND_SHAO_39,
	SOUND_SHAO_40,
	SOUND_SHAO_41,
	SOUND_SHAO_42,
	SOUND_SHAO_43,
	SOUND_SHAO_44,
	SOUND_SHAO_45,
	SOUND_SHAO_46,
	SOUND_SHAO_47,
	SOUND_SHAO_48,
	SOUND_SHAO_49,
	SOUND_SHAO_50,
	SOUND_SHAO_51,
	SOUND_SHAO_WIN_SCREAM,
	SOUND_SHAO_53,
	SOUND_SHAO_54,
	SOUND_SHAO_55,
	SOUND_SHAO_WIN_LAUGHTER,
	SOUND_SHAO_57,
	SOUND_GORO_AMOUNT = 40,
	SOUND_GORO_SELECT = 7536,
	SOUND_GORO_WINS,
	SOUND_DRAHMIN_SELECT,
	SOUND_DRAHMIN_WINS,
	SOUND_DRAHMIN_AMOUNT = 4,
	SOUND_SAREENA_SELECT = 7544,
	SOUND_SAREENA_WINS,
	SOUND_QUAN_SELECT = 7549,
	SOUND_QUAN_WINS,
	SOUND_SAREENA_AMOUNT = 7,
	SOUND_SHANG_TSUNG_SELECT = 7558,
	SOUND_SHANG_TSUNG_WINS,
	SOUND_SHANG_TSUNG_AMOUNT = 5,
	SOUND_KUNG_LAO_SELECT = 7564,
	SOUND_KUNG_LAO_WINS,
	SOUND_KUNG_LAO_AMOUNT = 4,
	SOUND_CAGE_SELECT = 7570,
	SOUND_CAGE_WINS,
	SOUND_CAGE_AMOUNT = 4,
	SOUND_RAIN_SELECT = 7577,
	SOUND_RAIN_WINS,
	SOUND_RAIN_AMOUNT = 5,
	SOUND_NITARA_SELECT = 7583,
	SOUND_NITARA_WINS,
	SOUND_NITARA_AMOUNT = 4,
	SOUND_SEKTOR_SELECT = 7589,
	SOUND_SEKTOR_WINS,
	SOUND_SEKTOR_AMOUNT = 4,
	TOTAL_NEW_SOUNDS = 106 + SOUND_GORO_AMOUNT + SOUND_DRAHMIN_AMOUNT + SOUND_SAREENA_AMOUNT + SOUND_SHANG_TSUNG_AMOUNT + SOUND_KUNG_LAO_AMOUNT
	+ SOUND_CAGE_AMOUNT + SOUND_RAIN_AMOUNT+ SOUND_NITARA_AMOUNT + SOUND_SEKTOR_AMOUNT,
	VOICE_AMOUNT = 92,
	NEW_VOICES = 2
};

extern sound_entry mk_sound_table[TOTAL_SOUNDS];

void init_sound_hook();

#ifndef  PS2_BUILD
void dump_sound_table();
#endif // ! PS2_BUILD

